name: build
on:
- push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v1 
        with:
          registry: "ghcr.io"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}
      - name: Build and export to Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: baw-appie/b6t:test
      - name: Run test
        run: |
          sudo mkdir /b6t-test
          cd /b6t-test
          docker run -d -p 127.0.0.1:3000:3000 --name b6t -v "$PWD/b6t-data:/data" baw-appie/b6t:test
          sleep 5

          sudo mkdir -p ./b6t-data/minio/apps/hello
          echo 'Router.get("/", () => new Response("Hello from b6t"))' | sudo tee ./index.js
          sudo tar -cvf ./b6t-data/minio/apps/hello/1.tar ./index.js
          echo '{"version":"1","package":"hello/1.tar","env":{}}' | sudo tee ./b6t-data/minio/apps/hello/metadata.json

          curl -H "X-Blueboat-Metadata: hello/metadata.json" http://localhost:3000 | grep "Hello from b6t"
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/baw-appie/b6t:v0.2.14-alpha.1
          labels: ${{ steps.meta.outputs.labels }}
